algoritmo "ConversãoHoras"
// Função : converter horas em minutos
// Autor : agatha louzada
// Data : 10/05/2022
// Seção de Declarações 
var
hora,minuto:inteiro
resultado: real
inicio
// Início
escreval("Digite a hora: ")
leia(hora)
escreval("Agora digite os minutos: ")
leia(minuto)
resultado <- minuto/60 + hora
escreval("O resultado da operação é : ",resultado)





 
fimalgoritmo
