algoritmo "Algoritmo Valor e Quantidade"
// Função : calcular media das notas
// Autor : agatha louzda
// Data : 26/04/2022
// Seção de Declarações
var
qntd,valor,vt:real
inicio
escreval("Digite a quantidade de peças: ")
leia(qntd)
escreval("Digite o valor de cada peça: ")
leia(valor)
//FIM DOS DADOS DE ENTRADA

//PROCESSAMENTO
vt <- qntd * valor
// FIM PROCESSAMENTO

//DADOS DE SAÍDA
escreval("o valor total das peças é de:",vt)


fimalgoritmo
