algoritmo "Algoritmo CalculaMédia"
// Função : calcular media das notas
// Autor : agatha louzda
// Data : 26/04/2022
// Seção de Declarações
var
media,p1,p2:real
inicio
escreval("Digite a primeira nota")
leia(p1)
escreval("Digite a segunda nota")
leia(p2)
//FIM DOS DADOS DE ENTRADA

//PROCESSAMENTO
media <-(p1+p2)/2
// FIM PROCESSAMENTO

//DADOS DE SAÍDA
escreval("A sua média é de: ",media)


fimalgoritmo
