algoritmo "semnome"
// Função :
// Autor :
// Data : 21/06/2022
// Seção de Declarações 
var
nome:caracter
n1,n2,n3:real
NF:real
inicio
escreval("Olá,qual é seu nome: ")
leia(nome)
escreval("Digite a nota total do seu trabalho: ")
leia(n1)
escreval("Agora digite a nota da sua primeira prova: ")
leia(n2)
escreval("E por fim,a nota da sua segunda prova: ")
leia(n3)

NF <- (n1+n2+n3)/3
escreval("Sua nota aritmética é: ",NF)






fimalgoritmo
