algoritmo "Exemplo_01"
// Função :Exemplo de convencional
// Autor : Ágatha louzada
// Data : 26/07/2022
// Seção de Declarações 
var
idade:inteiro
inicio
// Seção de Comandos 
escreval("Entre com a idade: ")
leia(idade)
se idade>=18 entao
   escreval("PODE PASSAR")
   escreval("VERDADEIRO")
 senao
   escreval("NAO PODE PASSAR")
   escreval("FALSO")
fimse
   escreval("ACABOOUU...")
fimalgoritmo
